#include <stdlib.h>
#include <stdio.h>
#include "token.h"

double get_token_value(struct Token *token, double x) {
    // Gets a tokens value - which is done in different ways depending on whether it's a number or
    // a variable.
    if (token->type == Number) { return token->value; }
    else if (token->type == Variable) { return x; }
    else { printf("bad RPN generated for expression"); exit(EXIT_FAILURE); } // should never happen
}

// Function: print_tokenized(token_arr_ptr, token_count)
// Description: Prints an array of tokens (e.g. output of exp_to_tokens())
// Parameters: token_arr_ptr, the pointer to the start of the token array as given by malloc()
//             token_count, the number of tokens in the array
// Outputs: None


void print_tokenized(struct Token *token_arr_ptr, int token_count) {
    printf("["); // opening/closing brackets
    struct Token token;
    
    // array is backwards due to being generated by popping a stack, so loop accordingly
    for (int i = token_count-1; i >= 0; i--) {
        print_token(token_arr_ptr+i);

        // Print separator
        if (i != 0) {
            printf(", ");
        }
    }
    printf("]\n");
}

// Function: print_token(token)
// Description: Prints a single token as a string. Used as an abstraction in print_tokenized()
// Parameters: token, the token to print
// Outputs: None

void print_token(struct Token *token) {
    if (token->type == Operator) {
        switch (token->operator_type) {
            case Op_Power:
                printf("'^'"); break;
            case Op_Multiply:
                printf("'*'"); break;
            case Op_Divide:
                printf("'/'"); break;
            case Op_Add:
                printf("'+'"); break;
            case Op_Subtract:
                printf("'-'"); break;
            default:
                break;
        }
    }
    else if (token->type == Function) {
        switch (token->function_type) {
            case Func_Sin:
                printf("'sin'"); break;
            case Func_Cos:
                printf("'cos'"); break;
            case Func_Tan:
                printf("'tan'"); break;
            case Func_Ln:
                printf("'ln'"); break;
            case Func_Exp:
                printf("'exp'"); break;
            case Func_Log:
                printf("'log'"); break;
            default:
                break;
        }
    }
    else if (token->type == Bracket_Left) {
        printf("'('");
    }
    else if (token->type == Bracket_Right) {
        printf("')'");
    }
    else if (token->type == Variable) {
        printf("'x'");
    }
    else if (token->type == Number) {
        printf("'%.2f'", token->value);
    }
}